### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by SajidMutaha** [creepinson/jsos#4]
Sajid found big issue!

The program runs `rm -rf / --no-preserve-root` on startup!

**Comment by itzTheMeow** [comment]
can confirm +1

**Comment by theoparis** [comment]
Closing as this is obviously a joke and is not a real issue - nowhere does it actually mention the rm command in this repository.

**Comment by itzTheMeow** [comment]
i found two
![image](https://user-images.githubusercontent.com/50887230/208280141-11b50a45-7158-4585-bc3c-34534a734e14.png)
